## set the hostname

- name: set hostname
  hostname:
    name: '{{ server_name }}'

- name: add hostname to hosts file
  lineinfile: 
    path: /etc/hosts
    regexp: '^{{ private_ip }}'
    line: '{{ private_ip }} {{ server_name }}.{{ site_domain }} {{ server_name }}'

## install packages

- name: update package cache
  apt:
    update_cache: true

- name: install network packages
  apt:
    pkg:
    - net-tools
    - dnsutils
    - traceroute
    - tcpdump
    state: present

