- name: install wireguard-tools
  apt:
    name: wireguard-tools
    state: present

- name: install wireguard config file
  template:
    src: wireguard.conf
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0440
  notify:
    - restart wireguard

